image: node:alpine

stages:
  - test
  - deploy

# TEST
test:
  stage: test
  script:
    - npm ci
    - npm test
  dependencies: 
    - build
  cache:
    paths:
      - node_modules

deploy:
  stage: deploy
  environment:
    name: production
    url: https://www.npmjs.com/package/@comeon/eslint-config
  script:
    - npm ci
    - npm pack
    # - npm publish --access public
  dependencies: 
    - build
  only:
    - master
    - tag
