image: node:alpine

stages:
  - build
  - test
  - deploy

# BUILD
build:
  stage: build
  script:
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

# TEST
test:
  script:
    - npm test
  stage: test
  cache:
    paths:
      - node_modules

deploy:
  stage: deploy
  environment:
    name: production
    url: https://www.npmjs.com/package/@comeon/eslint-config
  script:
    - npm pack
  dependencies: 
    - build
  only:
    - master
