image: node:alpine

stages:
  - build
  - test
  - deploy

# BUILD
build:
  stage: build
  script:
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

# TEST
test:
  script:
    - npm test
  stage: test
  cache:
    paths:
      - node_modules

